kind: PersistentVolume
apiVersion: v1
metadata:
  name: registry-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/registry"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: registry
  name: registry-pv-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi